outputpath: experiments/superkws
audioset_train_data: data/balanced_ssd.csv
kws_train_data: data/train/xiaoai_train.tsv
audioset_eval_data: data/eval_ssd.csv
kws_test_data: data/test/test_xiaoai.tsv
num_classes: 528
sampler: null
mixup: null
batch_size: 32
optimizer: Adam8bit
optimizer_args:
    lr: 0.001
    weight_decay: 0.0000005
epochs: 1000
early_stop: 1000
model: audio_transformer_h128_d6_m3_relu
model_args:
  target_length: 301
pretrained: pretrained/audio_transformer_h128_m3_d12_chunk10s_AS.pt
epoch_length: 10000
warmup_iters: 1000
chunk_length: 3.0
psl:
  model: MobileNetV2
  pretrained: pretrained/mobilenetv2_dm_mAP42_15.pt
loss: BCELoss
loss_args: {}
spectransforms:
    - TimeMasking:
        time_mask_param: 30
        iid_masks: True
    - FrequencyMasking:
        freq_mask_param: 8
        iid_masks: True
    - FrequencyMasking:
        freq_mask_param: 8
        iid_masks: True
wavtransforms:
  Shift:
    min_shift: -0.5
    max_shift: 0.5
  Gain:
    p: 0.5
  PolarityInversion:
    p: 0.5
